### ISSUE TITLE
Auto toggle when clicking [Enhancement]

### ISSUE THREAD

**Issue by Felix14-v2** [uku3lig/nowheel#1]
Hi! I often accidentally touch the mouse wheel when I place or break blocks using drag-click, and this gets me into trouble. But I would not like to completely disable the wheel, and toggling it is an ideal option. However, it is usually inconvenient to press a separate button to switch the mode, and I would like to suggest adding automatic disabling of the mouse wheel for 0.1-0.3 seconds (or for a preset time) after right or left click (it is better to be able to configure both mouse buttons separately). It would help a lot, for example, in building.

**Comment by uku3lig** [comment]
This seems something not too hard to implement, I'll take a look at it later.
